version: '3'

services: 

  nginx:
    build:
      context: nginx
    container_name: nginx
    entrypoint: dockerize -wait tcp://app:3000 -timeout 60s
    command: nginx -g 'daemon off;'
    networks:
        - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s
    command: node index.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    expose:
      - "3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    # volumes: 
    #   - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=fullcycle_devops_docker
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    expose: 
      - "3306"
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge 